- lastupdate.tmp
- models/solicitud_materias.go
- models/trabajo_grado.go
> #21572# Campo periodo academico

- .gitignore
- controllers/creditos.go
- controllers/creditos_materias.go
- controllers/cupos.go
- controllers/evaluadores.go
- controllers/fechas.go
- controllers/verificarRequisitos.go
- lastupdate.tmp
- main.go
- sonar-project.properties
- swagger/swagger.json
- swagger/swagger.yml
Merge cambios hechos en la rama dev para primera revisión
> Merge rama dev

- .drone.yml
- .drone.yml.backup
- .gitignore
- Dockerfile
- README.md
- conf/app.conf
- controllers/creditos.go
- controllers/creditos_materias.go
- controllers/cupos.go
- controllers/evaluadores.go
- controllers/fechas.go
- controllers/verificarRequisitos.go
- entrypoint.sh
- golog/golog_comprobacion.go
- main.go
- models/creditos_materias.go
- models/cupos.go
- models/modalidad.go
- models/predicado.go
- models/trabajo_grado.go
- routers/commentsRouter_controllers.go
- routers/router.go
- sonar-project.properties
- tests/default_test.go
merge de test con master @corio27
> merge de test con master 

- .drone.yml
Se coloca en comentario el check readme , pues no se ha creado el archivo previamente
> Fix: Se coloca en comentario el check readme , pues no se ha creado el archivo previamente

- .drone.yml
Se coloca en comentario el check readme y se actualiza el go run  test , pues no se ha creado el archivo previamente y esta antiguo el go run test
> fix: Se coloca en comentario el check readme y se actualiza el go run  test , pues no se ha creado el archivo previamente

- controllers/verificarRequisitos.go
Se arregla aspectos con respecto al guardado de los estados de grado
> fix: Se arregla aspectos con respecto al guardado de los estados de grado

- .drone.yml
fix: Se cambia toda la versión de Go del archivo drone a 1.18
> fix: Se cambia toda la versión de Go del archivo drone a 1.18

- controllers/verificarRequisitos.go
fix: Se agrega la sección del caso nueve para que reconozca la pasantía interna.
> fix: Se agrega la seccion del caso nueve para que reconozca la pasantia interna.

- controllers/verificarRequisitos.go
fix: Se realiza impresión del resultado de la función verificarRequisitos.
> fix: Se realiza impresión del resultado de la función verificarRequisitos.

- .drone.yml
- controllers/evaluadores.go
- controllers/verificarRequisitos.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- Se hace envío del PR de los cambios en ambiente de pruebas a producción
> Despliegue en Producción

- conf/app.conf
- helpers/tr_respuesta_solicitud.go
- models/DominioTipoDocumento.go
- models/tipo_documento.go
> feat: Se agrega funcionalidad de almacenar documento Anteproyecto

- helpers/tr_respuesta_solicitud.go
> fix:se corrige objeto para que cumpla con la sintaxis de DetallePansantia

- helpers/tr_respuesta_solicitud.go
- models/detalle_pasantia.go
> feat: Se agrega funcionalidad para almacenar documentos de pasantia

- controllers/tr_subir_arl.go
- helpers/tr_subir_arl.go
- models/tr_subir_arl.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
> feat: Se crea tr_subir_arl 

- helpers/tr_respuesta_solicitud.go
> feat: Se agrega detalle_trabajo_grado a Pasantia 

- helpers/tr_respuesta_solicitud.go
> fix: Corrección al aprobar el cambio de director interno #567

- controllers/tr_registrar_acta_seguimiento.go
- helpers/tr_registrar_acta_seguimiento.go
- models/tr_registrar_acta_seguimiento.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
> feat: Se crea tr_registrar_acta_seguimiento 

- controllers/tr_respuesta_solicitud.go
- helpers/tr_respuesta_solicitud.go
- models/detalle_pasantia.go
> feat:Cargar hoja de vida director externo en tr_respuesta_solicitud 

- go.mod
- go.sum
- helpers/tr_respuesta_solicitud.go
> feat: Solicitud cambio Director Externo 

- controllers/evaluadores.go
- controllers/verificarRequisitos.go
- go.mod
- go.sum
- helpers/tr_respuesta_solicitud.go
> feat: Cambio código abreviación Pasantía

- .drone.yml
- controllers/reporte_general.go
- helpers/reporte_general.go
- models/reporte_general.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
udistrital/polux_cliente/issues/641
> Feature/ Reporte General

- helpers/tr_respuesta_solicitud.go
- models/tr_respuesta_solicitud.go
udistrital/polux_cliente/issues/714
udistrital/polux_cliente/issues/716
> feature: Subir anexos a la tabla documento_escrito BD #714

- controllers/reporte_general.go
- controllers/reporte_solicitud.go
- helpers/reporte_general.go
- helpers/reporte_solicitud.go
udistrital/polux_cliente/issues/730
> Feature/Reportes Base 64

- controllers/creditos.go
- controllers/creditos_materias.go
- controllers/cupos.go
- controllers/evaluadores.go
- controllers/fechas.go
- controllers/reporte_general.go
- controllers/tr_registrar_acta_seguimiento.go
- controllers/tr_registrar_revision_tg.go
- controllers/tr_respuesta_solicitud.go
- controllers/tr_solicitud.go
- controllers/tr_subir_arl.go
- controllers/tr_vinculado_registrar_nota.go
- controllers/verificarRequisitos.go
- helpers/evaluadores.go
- helpers/reporte_general.go
- helpers/tr_registrar_acta_seguimiento.go
- helpers/tr_registrar_revision_tg.go
- helpers/tr_respuesta_solicitud.go
- helpers/tr_solicitud.go
- helpers/tr_subir_arl.go
- helpers/tr_vinculado_registrar_nota.go
- helpers/utilidades.go
- main.go
fix: se realizan ajustes para manejo correcto de respuestas y ejecución de rollbacks udistrital/polux_cliente#728
> fix: se realizan ajustes para manejo correcto de respuestas y ejecución de rollbacks

- controllers/reporte_general.go
- controllers/reporte_solicitud.go
- helpers/reporte_general.go
- helpers/reporte_solicitud.go
udistrital/polux_cliente/issues/761
> Feature/Response Reports

- controllers/verificarRequisitos.go
> fix: Se actualiza la estructura de respuesta en verificarRequisitos 

- .drone.yml
- helpers/tr_registrar_revision_tg.go
- models/revision_trabajo_grado.go
- models/vinculacion_trabajo_grado.go
- sonar-project.properties
> fix: Se corrigen los errores reportados en las pruebas de carga y seguridad

- controllers/tr_solicitud.go
- models/solicitud_trabajo_grado.go
Se desarrolla tratamiento datos personales arl en solicitud_trabajo_grado pasantía interna issue udistrital/polux_cliente#760
> feat: se desarrolla tratamiento datos personales arl

- helpers/tr_respuesta_solicitud.go
> fix: Correccion error cambio de vinculado 

- controllers/verificarRequisitos.go
- golog/golog_comprobacion.go
- helpers/tr_respuesta_solicitud.go
- helpers/tr_vinculado_registrar_nota.go
https://github.com/udistrital/polux_cliente/issues/791
> fix: Correccion errores Sonarqube

- helpers/tr_respuesta_solicitud.go
- models/vinculacion_trabajo_grado.go
> feat: Se agrega funcionalidad para almacenar codigo abreviacion de vinculado

- helpers/tr_respuesta_solicitud.go
- models/tr_respuesta_solicitud.go
udistrital/polux_cliente/issues/861
> feature: Creación del Trabajo de Grado según campo MateriasProPos

- helpers/tr_respuesta_solicitud.go
- models/documentos_materias.go
- models/tr_trabajo_grado.go
> feat: Se agrega funcionalidad para almacenar documentos de Posgrado

- helpers/tr_respuesta_solicitud.go
- models/espacio_academico_inscrito.go
- models/tr_respuesta_solicitud.go
> feat: se almacena nombre carrera posgrado 

- helpers/tr_respuesta_solicitud.go
> feat:Desarrollo rollbacks espacio_academico_inscrito
